# publish on npm when there is a new version tag

name: publish
on:
  push:
    tags: [v*]

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          registry-url: "https://registry.npmjs.org"
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: install dependencies
        run: yarn install
      - name: build
        run: yarn build
      - name: run test
        run: yarn test
      - name: generate changelog
        uses: orhun/git-cliff-action@v1
        id: git-cliff
        with:
          args: -vv --latest --strip header
        env:
          OUTPUT: CHANGES.md
      - name: save changelog
        id: changelog
        shell: bash
        run: |
          r=$(cat ${{ steps.git-cliff.outputs.changelog }})
          r="${r//'%'/'%25'}"     # Multiline escape sequences for %
          r="${r//$'\n'/'%0A'}"   # Multiline escape sequences for '\n'
          r="${r//$'\r'/'%0D'}"   # Multiline escape sequences for '\r'
          echo "::set-output name=CHANGELOG::$r"
      - name: create release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.changelog.outputs.CHANGELOG }}
          draft: false
          prerelease: false
      - name: npm publish
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
